// src/state.js — every piece of mutable app state (docs/split-plan.md §2.1).
// No imports: this file evaluates first, so every S field exists before any
// app code runs (removes the boot-path TDZ class of bug for state).
export const S = {
  APP_BASE: (() => { // let: the vm tests pin it (no location there)
  try { return new URL(".", location.href).href; } catch (e) { return ""; }
})(),
  APP_MODE: null,
  vwOpenGroup: null,
  fileOpenRecentOpen: false,
  CATALOG: {},
  kitShowAll: localStorage.getItem("ff1roll-kitshowall") === "1",
  _kitSlots: null,
  _laneTop: null,
  laneOverride: null,
  _autoColorCache: { key: "", colors: [] },
  playRate: 1,
  song: null,
  songKey: null,
  songViewRedraw: null,
  catalogRefreshedAt: 0,
  trackState: [],
  selTrack: 0,
  selNote: null,
  mode: null,
  pencilDur: 0.5,
  gridDiv: null,
  gridAnchor: {b: 1, q: 1},
  _has32: null,
  pencilVel: 80,
  pencilAcc: "key",
  editUndo: [],
  view: { x: 0, y: 0, pxq: 56, rowH: 13 },
  playing: false,
  playT0: 0,
  playOffset: 0,
  schedIdx: 0,
  schedEvents: [],
  raf: 0,
  schedTimer: 0,
  loopSeg: null,
  loopPass: 0,
  audio: null,
  master: null,
  trackGains: [],
  trackPanners: [],
  mixerMeterEls: [],
  mixerMasterMeterEl: null,
  mixerAnalysers: [],
  mixerMeterBufs: [],
  mixerMasterAnalyser: null,
  mixerMasterMeterBuf: null,
  mixerMeterRaf: 0,
  mixerMeterRunning: false,
  mixerMeterLastT: 0,
  mixerStripEls: [],
  mixerDrag: null,
  songEndTick: 0,
  rollnotes: [],
  rollnotesReadOnly: false,
  rollnotesLockReason: null,
  rollnotesOrigin: null,
  playCursor: 0,
  editingNote: null,
  rangeSel: null,
  tapBand: {n: null, t: 0},
  lassoMode: false,
  instOpen: false,
  fallOn: false,
  subOn: localStorage.getItem("ff1roll-sub") !== "0",
  lassoRect: null,
  cmp: null,
  multiSel: [],
  multiSelKey: new Set(),
  multiSelSf: 0,
  keyRegions: [],
  declaredTs: null,
  previewSf: null,
  RULER_W: null,
  RULER_H: null,
  STRIP_Y: null, // top of the playhead strip (old RULER_H meaning: ruler + section/chord/analysis rows + audio strip — no strip). RULER_H = STRIP_Y + STRIP_H, see app.js

  secMaxDepth: 0,
  analysisOn: false,
  analysisBands: {chords: [], key: null},
  analysisChordLane: null,
  analysisKeyLane: null,
  _analysisTimer: null,
  analyzeTarget: null,
  sectionColors: {},
  PMIN: 24,
  PMAX: 96,
  chopS: 0,
  chopE: null,
  appliedChop: null,
  lastSubtitle: null,
  _idbQueue: Promise.resolve(),
  hlOn: localStorage.getItem("ff1roll-hl") === "1",
  lcdCache: "",
  loadGen: 0,
  songLoading: false,
  pendingPlay: false,
  trackExpand: false,
  sceneCanvas: null,
  sceneValid: false,
  sceneVX: -1,
  sceneVY: -1,
  phLastX: null,
  challengeSec: null,
  selOctaves: localStorage.getItem("ff1roll-seloct") !== "0",
  tracksGhost: null,
  selClip: null,
  noteClipboard: null,
  annoClipboard: [],
  lassoAnno: null,
  dupPending: null,
  insUnit: "bars",
  infoCopyText: null,
  infoFull: "tap a note",
  jobs: [],
  pubJobShown: null,
  logSeq: 0,
  srLastText: "",
  srLastAt: -1e9,
  srTimer: null,
  statusHistory: [],
  statusSeq: 0,
  drag: null,
  pinch: null,
  followFree: false,
  lastTapEnd: 0,
  masterVol: 1,
  clockProbe: null,
  wakeInFlight: false,
  sfOfflineCtx: null,
  sfPreloadPending: false,
  pulse25: null,
  pulse12: null,
  organWave: null,
  pluckCache: {},
  voiceMenuTi: -1,
  voiceMenuRenderToken: 0,
  voiceMenuGroup: null,
  voiceMenuGameVault: null,
  voiceMenuGameSys: null,
  voiceMenuGameSub: null,
  voiceMenuSf2Slug: null,
  instPlaySync: null,
  exporting: false,
  playGateTimer: null,
  playGateSince: 0,
  playGateShown: false,
  chipWorker: null,
  chipPreviewReq: 0,
  audioSrcs: [],
  autoAlignFiles: new Set(),
  stretchWorker: null,
  stretchJobId: 0,
  albumRun: null,
  albumEndAbs: null,
  albumFading: false,
  editOn: false,
  listenerMode: false,
  viewMode: localStorage.getItem("ff1roll-view") || "roll",
  scoreModel: null,
  scoreCache: new Map(),
  scoreZoom: 0,
  scoreIntro: null,
  currentPath: null,
  _keyEstCache: null,
  metGain: null,
  metTimer: 0,
  metNext: 0,
  metIdx: 0,
  metLastWhen: -1,
  metTaps: [],
  cofSf: 0,
  cofRot: 0,
  cofDragRot: null,
  chordRoot: 0,
  chordQual: "maj",
  chordOct: 4,
  chordInsDur: 1,
  mvFromFilter: null,
  cofPtr: null,
  findPc: null,
  challengeCopy: "",
  editrowHidden: false,
  footerHidden: false,
  fitReadlineScheduled: false,
  pendingMidis: null,
  audioReplaceTi: null,
  pencilNV: 8,
  pencilMod: 1,
  instTab: "piano",
  instFlash: null,
  instPtrOn: false,
  instLastP: null,
  instInfoTimer: 0,
  recording: false,
  recTake: [],
  recPending: new Map(),
  midiReady: false,
  midiAccess: null,
  midiErr: null,
  nativeMidiNames: [],
  micRec: null,
  micPrev: null,
  micBtn: null,
  rebarArmed: false,
  albumOrderPref: localStorage.getItem("ff1roll-albumorder") === "az" ? "az" : "game",
  pubCheckRunning: false,
  dropUpOpen: null,
  instPlayModule: null,
  sf2PlayModule: null,
  instNav: {sys: null, game: null, sub: null},
  instNavToken: 0,
  nsfSess: null,
  dpPattern: null,
  drTakes: [],
  drActive: -1,
  bsTakes: [],
  bsActive: -1,
  ptTarget: 0,
  editRedo: [],
  editBtnCache: "",
  askBusy: null,
  askModelCache: null,
  askSpanFrozen: null,
  aiWebllm: null,
  aiEngine: null,
  aiEngineModel: null,
  askSentPending: {},
  askGeneral: false,
  askTerminal: false,
  askCaps: {bridge: false, terminal: false, sessions: false},
  askSeenPending: {},
  askInboxNo: "",
  askInboxTimer: null,
  askStatusNow: null,
  askStatusRecent: [],
  askStatusNo: "",
  askStatusRecentOpen: false,
  askStatusCommits: null,
  askStatusCommitsAt: 0,
  askQuota: null,
  backupFlushTimer: null,
  deployAt: 0,
  deployTimer: null,
  deployHeld: false,
  askSessionCache: {},
  askShotPending: [],
  askDraftKey: null,
  askDraftTimer: null,
  askComposingAt: 0,
  askComposingOn: false,
  askJobsCache: null,
  askTerminalFast: 0,
  askTerminalTimer: null,
  askResumeTimer: null,
  wm: null,
  wmSideMembers: {left: [], right: []},
  wmBottomEls: [],
  filesMirrorT: 0,
  syncReturnToList: false,
};
