// tools/split/e2e-footer.mjs — the generated e2e accessor footer
// (`export const __nrExpose$ = {get, set}`) appended to src/app.js, shared by
// tools/split/cutover.mjs (step 0b: first write, over the freshly extracted
// body) and tools/split/regen-e2e-footer.mjs (step 1 on: every later change
// to app.js's top-level names — promote-state.mjs moving `let`s to `S`,
// a future move.mjs carving out a module — must regenerate this block,
// since it's static generated text written into app.js, not computed at
// runtime the way tests/harness.mjs's per-module footer is (docs/split-
// plan.md §3.2); drifting it silently produces a stale accessor that
// references a name no longer declared in app.js, which tools/split/
// check.mjs's rule 1 (free identifiers) catches statically. Node-only
// tooling, never shipped.
import { parseModule, declaredNames } from "./scope.mjs";

// The literal text every generated footer starts with (see addAccessorFooter
// below) — used by stripFooter to cut a stale footer back off before
// regenerating it from app.js's current body.
export const FOOTER_MARKER = "\n// ---- e2e accessor mirror (docs/split-plan.md §4 step 0b deviation) -------";

/** Removes a previously generated footer from `body`, if present (idempotent:
 *  a body with no footer is returned unchanged). */
export function stripFooter(body) {
  const i = body.indexOf(FOOTER_MARKER);
  return i === -1 ? body : body.slice(0, i);
}

/** Every top-level declared name in `body`, with whether it can be
 *  reassigned (function/class declarations and non-const variables are —
 *  ES modules allow rebinding a top-level function/class the same as
 *  `let`). Mirrors tests/harness.mjs's moduleMeta() (§3.2's footer), which
 *  solves the identical problem for the vm test harness. */
export function topLevelAccessorNames(body) {
  const { ast } = parseModule(body, "src/app.js (e2e-footer)");
  const names = [];
  for (const node of ast.body) {
    const declared = declaredNames(node);
    if (!declared.length) continue;
    const mutable = node.type === "FunctionDeclaration" || node.type === "ClassDeclaration"
      || (node.type === "VariableDeclaration" && node.kind !== "const");
    for (const name of declared) names.push({ name, mutable });
  }
  return names;
}

/** Appends `export const __nrExpose$ = {get, set}` covering every top-level name
 *  in `body` (docs/split-plan.md §4 step 0b deviation — see the file-header
 *  comment). Bare references inside the generated closures resolve to
 *  app.js's OWN top-level bindings, because this text is appended to that
 *  same module's source before anything parses it — identical to how
 *  tests/harness.mjs's per-module footer already works (§3.2). Never
 *  touches production unless src/devtools.js's exposeGlobals() is called
 *  (window.__NR_EXPOSE gate, src/main.js). Idempotent: strips any existing
 *  footer first, so calling this on an already-footed body regenerates it
 *  from the CURRENT top-level names rather than double-appending. */
export function addAccessorFooter(body) {
  const stripped = stripFooter(body);
  const names = topLevelAccessorNames(stripped);
  if (!names.length) return stripped; // nothing declared — nothing to mirror
  const gets = names.map(({ name }) => `${JSON.stringify(name)}: () => ${name}`).join(", ");
  const sets = names.filter(n => n.mutable).map(({ name }) => `${JSON.stringify(name)}: (v) => (${name} = v)`).join(", ");
  const footer = `${FOOTER_MARKER}
// Generated by tools/split/cutover.mjs (step 0b) / tools/split/
// regen-e2e-footer.mjs (step 1 on), not hand-maintained — re-running either
// regenerates this block from app.js's CURRENT top-level names, so it never
// drifts. app.js is the legacy container: as module-split steps carve real
// modules out of it, its remaining top-level names shrink (step 1's
// promote-state.mjs moved ~257 of them to \`S\`; later steps move functions
// to their own modules, where a real \`export\` replaces this mirror for
// them), so without regenerating this block after a change, src/devtools.js's
// window mirror would offer a stale accessor referencing a name no longer
// declared here — a free-identifier violation tools/split/check.mjs's rule 1
// catches statically, and a ReferenceError at runtime if it weren't. get
// covers every top-level name; set covers the mutable ones (function/class
// declarations and non-const variables — ES modules allow reassigning those,
// same as \`let\`). Identical technique to tests/harness.mjs's own per-module
// footer (§3.2), which already solves this for the vm test harness — but a
// DIFFERENT name (__nrExpose$, not __nr$): tests/harness.mjs's module-mode
// loader blindly appends its OWN __nr$ footer to every src/ file it loads
// (including app.js, as a test fixture), so reusing that name here would
// double-declare it the moment a vm test loads this file. tools/split/
// check.mjs's rule 1 treats every name referenced here as already bound
// (they're this module's own top-level declarations), so this block does
// not introduce free-identifier findings.
export const __nrExpose$ = {get: {${gets}}, set: {${sets}}};
`;
  return stripped + footer;
}
